# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('category', models.IntegerField(max_length=10, verbose_name='\u7c7b\u522b')),
                ('title', models.CharField(max_length=256, verbose_name='\u6807\u9898')),
                ('content', models.TextField(blank=True, default='', verbose_name='\u5185\u5bb9')),
                ('published', models.BooleanField(default=True, verbose_name='\u6b63\u5f0f\u53d1\u5e03')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('permission', models.IntegerField(max_length=10, verbose_name='\u6743\u9650')),
                ('auth', models.CharField(max_length=40, verbose_name='\u4f5c\u8005')),
                ('pwd', models.CharField(max_length=256, verbose_name='\u5bc6\u7801')),
                ('email', models.CharField(max_length=40, verbose_name='\u90ae\u7bb1')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='auth_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.User'),
        ),
    ]
