# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_auto_20170507_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='auth_name',
            field=models.CharField(default='admin', max_length=10, verbose_name='\u4f5c\u8005'),
        ),
    ]
